version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Etc/UTC
  open-pull-requests-limit: 10
  reviewers:
  - str4d
  assignees:
  - str4d
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: Etc/UTC
  open-pull-requests-limit: 10
  reviewers:
  - str4d
  assignees:
  - str4d
