name: CI checks

on: [push, pull_request]

jobs:
  build:
    name: Test with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [10, 11, 12, 13, 14]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test
      run: ./gradlew build

  build-old:
    name: Test with Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [7, 8, 9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up target Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Set TARGET_JAVA_HOME
      run: echo "::set-env name=TARGET_JAVA_HOME::$JAVA_HOME"
    - name: Set up Java 10 for running Gradle
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test
      run: ./gradlew build
